language: ruby
rvm:
  - 2.1.3
before_script:
  - echo 'Canada/Eastern' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - psql -c 'create database photoz_test;' -U postgres
notifications:
  email: false
